routes/web.php
<?php

use App\Http\Controllers\dashboard\AdminController;
use App\Http\Controllers\dashboard\CommentController;
use App\Http\Controllers\dashboard\FeatureController;
use App\Http\Controllers\dashboard\MessageContoller;
use App\Http\Controllers\ecommerce\CategoryController;
use App\Http\Controllers\ecommerce\ProductController;
use App\Http\Controllers\ecommerce\SubCategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\landing_page\LandingPageController;
use App\Http\Helpers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

////Auth::routes();
//
//
//
//Route::prefix('admin')->name('admin.')->group(function(){
//
//    Route::middleware(['guest:admin'])->group(function(){
//        Route::view('/login','admin.dashboard.admin.login')->name('login');
//        Route::post('/check',[AdminController::class,'check'])->name('check');
//    });
//
////    Route::middleware(['auth:admin'])->group(function(){
//////        Route::get('/home', [HomeController::class, 'index'])->name('home');
////        Route::post('/logout',[AdminController::class,'logout'])->name('logout');
////    });
//
//});


Route::post('admin/changeStatus/{model}', [HomeController::class,'changeStatus']);

Route::post('subcat', [CategoryController::class, 'subCat']);

Route::view('admin/login', 'admin.dashboard.admin.login')->middleware(['guest:admin']);
Route::post('admin/check', [AdminController::class, 'check'])->middleware(['guest:admin']);
Route::get('admin/dashboard/home/{local}', [HomeController::class, 'index'])->middleware(['auth:admin']);
Route::post('admin/logout', [AdminController::class, 'logout'])->middleware(['auth:admin']);



//
//
Route::get('admin/home/{local}', [HomeController::class, 'index'])->middleware(['auth:admin']);
Route::post('home/update', [HomeController::class, 'update'])->middleware(['auth:admin']);

Route::get('index/{local}',[LandingPageController::class,'index']);
Route::get('twitter/{local}',[LandingPageController::class,'twitter']);
Route::post('message/store',[LandingPageController::class,'storeMessage']);


Route::get('feature/index/{local}',[FeatureController::class,'index'])->middleware('auth:admin');
Route::get('feature/create/{local}',[FeatureController::class,'create'])->middleware('auth:admin');
Route::post('feature/store',[FeatureController::class,'store'])->middleware('auth:admin');
Route::get('feature/edit/{local}/{id}',[FeatureController::class,'edit'])->middleware('auth:admin');
Route::post('feature/update/{id}',[FeatureController::class,'update'])->middleware('auth:admin');
Route::get('feature/delete/{id}',[FeatureController::class,'destroy'])->middleware('auth:admin');

Route::get('comment/index/{local}',[CommentController::class,'index'])->middleware('auth:admin');
Route::get('comment/create/{local}',[CommentController::class,'create'])->middleware('auth:admin');
Route::post('comment/store',[CommentController::class,'store'])->middleware('auth:admin');
Route::get('comment/edit/{local}/{id}',[CommentController::class,'edit'])->middleware('auth:admin');
Route::post('comment/update/{id}',[CommentController::class,'update'])->middleware('auth:admin');
Route::get('comment/delete/{id}',[CommentController::class,'destroy'])->middleware('auth:admin');

Route::get('message/index/{local}',[MessageContoller::class,'index'])->middleware('auth:admin');
Route::get('message/delete/{id}',[MessageContoller::class,'destroy'])->middleware('auth:admin');

Route::get('admin/index/{local}',[AdminController::class,'index'])->middleware('auth:admin');
Route::get('admin/create/{local}',[AdminController::class,'create'])->middleware('auth:admin');
Route::post('admin/store',[AdminController::class,'store'])->middleware('auth:admin');
Route::get('admin/edit/{local}/{id}',[AdminController::class,'edit'])->middleware('auth:admin');
Route::post('admin/update/{id}',[AdminController::class,'update'])->middleware('auth:admin');
Route::get('admin/delete/{id}',[AdminController::class,'destroy'])->middleware('auth:admin');


Route::group(['prefix'=>'admin'],function (){

    if (Helpers::can('categories')) {
        Route::get('categories', [CategoryController::class, 'index']);
        Route::get('categories/create', [CategoryController::class, 'create']);
        Route::post('categories/store', [CategoryController::class, 'store']);
        Route::get('categories/{id}/edit', [CategoryController::class, 'edit']);
        Route::post('categories/{id}/update', [CategoryController::class, 'update']);
        Route::get('categories/{id}/delete', [CategoryController::class, 'destroy']);
    }

    if (Helpers::can('sub_categories')) {
        Route::get('sub-categories', [SubCategoryController::class, 'index']);
        Route::get('sub-categories/create', [SubCategoryController::class, 'create']);
        Route::post('sub-categories/store', [SubCategoryController::class, 'store']);
        Route::get('sub-categories/{id}/edit', [SubCategoryController::class, 'edit']);
        Route::post('sub-categories/{id}/update', [SubCategoryController::class, 'update']);
        Route::get('sub-categories/{id}/delete', [SubCategoryController::class, 'destroy']);
    }


    if (Helpers::can('products')) {
        Route::get('products', [ProductController::class, 'index']);
        Route::get('products/create', [ProductController::class, 'create']);
        Route::post('products/store', [ProductController::class, 'store']);
        Route::get('products/{id}/edit', [ProductController::class, 'edit']);
        Route::post('products/{id}/update', [ProductController::class, 'update']);
        Route::get('products/{id}/delete', [ProductController::class, 'delete']);
    }


});

app/Models/ecommerce/Category.php
<?php

namespace App\Models\ecommerce;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model implements TranslatableContract
{
    use HasFactory;
    public $translatedAttributes = ['name'];

    use SoftDeletes,Translatable;
    protected $table = 'categories';
    protected $fillable = ['image'];
    protected $hidden = ['updated_at', 'deleted_at','translations'];

    public function subcategories(){
        return $this->hasMany('App\Models\ecommerce\SubCategory', 'category_id');
    }

    public function getImageAttribute($value)
    {
        if($value){
            return url('uploads/images/category/'.$value);
        }else{
            return url('landing_page/images/est.png');
        }
    }
}

app/Models/ecommerce/CategoryTranslation.php
<?php

namespace App\Models\ecommerce;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CategoryTranslation extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['name'];
}

app/Models/ecommerce/Product.php
<?php

namespace App\Models\ecommerce;

use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;

    public $translatedAttributes = ['name', 'description'];
    use SoftDeletes, Translatable;

    protected $table = 'products';
    protected $fillable = ['image', 'price', 'discount', 'offer_from', 'offer_to'];
    protected $hidden = ['updated_at', 'deleted_at', 'translations'];


    public function attachments()
    {
        return $this->hasMany(ProductImage::class, 'product_id');
    }


    public function getAvailableOfferAttribute()
    {
        return $this->offer_from . ' ' . '_' . ' ' . $this->offer_to;

    }

    public function getFinalDiscountAttribute(){
        $offer_from = $this->offer_from;
        $offer_to = $this->offer_to;
        $discount=$this->discount;

        if ($offer_to >= now()->toDateString()&&$offer_from < now()->toString()&&$this->status=='active') {
            if ($discount!=null&&$discount>0) {
                return $discount;
            }
        }else{
            return 0;
        }
        }

    public function getPriceOfferAttribute()
    {
        $offer_from = $this->offer_from;
        $offer_to = $this->offer_to;
        if ( $offer_to >= now()->toDateString()&&$offer_from < now()->toString()&&$this->status=='active') {
            $price = $this->price;
            $discount = $this->discount;
            $discount = ($price * $discount) / 100;
            $newPrice = $price - $discount;
            return $newPrice;
        } else {
            return $this->price;
        }
    }

//    public function getDiscountAttribute()
//    {
//
//        $productoffer = $this->where('offer_from', '<=', now()->toDateString())->where('offer_to', '>=', now()->toDateString())->first();
//        if ($productoffer) {
//            return $productoffer->discount;
//        } else {
//            return 0;
//        }
//
//    }

    public function getLogoAttribute($value)
    {
        if ($value) {
            return url('uploads/images/products/' . $value);
        } else {
            return url('landing_page/images/est.png');
        }
    }
}

app/Models/ecommerce/ProductTranslation.php
<?php

namespace App\Models\ecommerce;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProductTranslation extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $fillable = ['name','description'];
}

app/Http/Controllers/ecommerce/CategoryController.php
<?php

namespace App\Http\Controllers\ecommerce;

use App\Http\Controllers\Controller;
use App\Models\ecommerce\Category;
use App\Models\ecommerce\SubCategory;
use App\Models\general\Language;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class CategoryController extends Controller
{
    function index()
    {
        $categories = Category::all();
        return view('ecommerce.category.index')->with(compact('categories'));
    }

    function create()
    {
        return view('ecommerce.category.create');

    }

    function store(Request $request)
    {

        $roles = [
            'image' => 'required|image|mimes:jpeg,jpg,png',
             'status'     => 'required',
            // 'name'     => 'required',
        ];
        $locales = Language::all()->pluck('lang');
        foreach ($locales as $locale) {
            $roles['name_' . $locale] = 'required|min:5';
        }
        $this->validate($request, $roles);
        $cat = new Category();
        foreach ($locales as $locale) {
            $cat->translateOrNew($locale)->name = $request->get('name_' . $locale);
        }
        if ($request['image'] != null) {
            $image = $request->file('image');
            $image_name = time() + rand(1, 1000000) . '.' . $image->getClientOriginalName();
            $image->move(public_path('/uploads/images/category/'), $image_name);
            $cat->image = $image_name;
        }
        $status = $cat->save();
        if ($status) {
            return redirect()->back()->with('success', __('cp.created_successfully'));
        } else {
            return redirect()->back()->with('error', __('cp.something_wrong'));
        }
    }

    function edit($id)
    {
        $category = Category::where('id', $id)->first();
        return view('ecommerce.category.edit')->with('category', $category);
    }

    public function update(Request $request, $id)
    {
        $roles = [
            'image' => 'image|mimes:jpeg,jpg,png',
            'status'     => 'required',

        ];
        $locales = Language::all()->pluck('lang');
        foreach ($locales as $locale) {
            $roles['name_' . $locale] = 'required|min:5';
        }
        $this->validate($request, $roles);
        $cat = Category::query()->findOrFail($id);
        foreach ($locales as $locale) {
            $cat->translateOrNew($locale)->name = $request->get('name_' . $locale);
        }
        if ($request['image'] != null) {
            $image = $request->file('image');
            $image_name = time() + rand(1, 1000000) . '.' . $image->getClientOriginalName();
            $image->move(public_path('/uploads/images/category/'), $image_name);
            $cat->image = $image_name;
        }
        $cat->save();
        $status = $cat->save();
        if ($status) {
            return redirect()->back()->with('success', __('cp.updated_successfully'));
        }
        return redirect()->back()->with('error', __('cp.something_wrong'));

    }


    public function subCat(Request $request)
    {

        $category_id = $request->cat_id;

        $subcategories = SubCategory::where('category_id',$category_id)
            //->with('subcategories')
            ->get();
        return response()->json([
            'subcategories' => $subcategories
        ]);
    }


    function destroy($id)
    {
        $item = Category::query()->findOrFail($id);
        if ($item) {
            $status = Category::query()->where('id', $id)->delete();
            if ($status)
            return redirect()->back()->with('success', __('cp.deleted_successfully'));
        }
        return redirect()->back()->with('error', __('cp.something_wrong'));
    }


}

app/Http/Controllers/ecommerce/SubCategoryController.php
<?php

namespace App\Http\Controllers\ecommerce;

use App\Http\Controllers\Controller;
use App\Models\ecommerce\SubCategory;
use App\Models\general\Language;
use Illuminate\Http\Request;

class SubCategoryController extends Controller
{
    function index(Request $request)
    {

        $subCategories = SubCategory::query();

        if ($request->has('category_id')) {

            if ($request->get('category_id') != null) {
                $subCategories = $subCategories->where('category_id', $request->get('category_id'));
            }

        }

        if ($request->has('status')) {
            if ($request->get('status') != null) {
                $subCategories->where('status', $request->get('status'));
            }

        }

        $subCategories = $subCategories->orderBy('id', 'desc')->get();//paginate(20);
        return view('ecommerce.sub_category.index', [
            'subCategories' => $subCategories,
        ]);
    }

    function create()
    {
        return view('ecommerce.sub_category.create');//->with(compact('categories'));
    }

    function store(Request $request)
    {

        $roles = [
            'image' => 'required|image|mimes:jpeg,jpg,png',
            'category_id' => 'required',
            'status' => 'required',
            // 'name'     => 'required',

        ];
        $locales = Language::all()->pluck('lang');
        foreach ($locales as $locale) {
            $roles['name_' . $locale] = 'required|min:5';
        }
        $this->validate($request, $roles);


        $sub = new SubCategory();
        $sub->category_id = $request->category_id;
        $sub->status = $request->get('status');

        foreach ($locales as $locale) {
            $sub->translateOrNew($locale)->name = $request->get('name_' . $locale);
        }

        if ($request['image'] != null) {
            $image = $request->file('image');
            $image_name = time() + rand(1, 1000000) . '.' . $image->getClientOriginalName();
            $image->move(public_path('/uploads/images/sub_category/'), $image_name);
            $sub->image = $image_name;
        }


//        $cat->sub_id = 0;

        $sub->save();
        return redirect()->back();


    }

    function edit($id)
    {
        $subCategory = SubCategory::where('id', $id)->first();
        return view('ecommerce.sub_category.edit')->with(compact('subCategory'));
    }

    function update(Request $request, $id)
    {
        $roles = [
            'image' => 'required|image|mimes:jpeg,jpg,png',
            'category_id' => 'required',
            'status' => 'required',
            // 'name'     => 'required',

        ];
        $locales = Language::all()->pluck('lang');
        foreach ($locales as $locale) {
            $roles['name_' . $locale] = 'required|min:5';
        }
        $this->validate($request, $roles);


        $sub = SubCategory::query()->findOrFail($id);
        $sub->category_id = $request->category_id;
        $sub->status = $request->get('status');

        foreach ($locales as $locale) {
            $sub->translateOrNew($locale)->name = $request->get('name_' . $locale);
        }

        if ($request['image'] != null) {
            $image = $request->file('image');
            $image_name = time() + rand(1, 1000000) . '.' . $image->getClientOriginalName();
            $image->move(public_path('/uploads/images/sub_category/'), $image_name);
            $sub->image = $image_name;
        }

        $sub->save();

        return redirect()->back()->with('status', __('cp.update'));
    }


    function destroy($id)
    {
        $item = SubCategory::query()->findOrFail($id);
        if ($item) {
            SubCategory::query()->where('id', $id)->delete();
            return redirect()->back()->with('success',"success");
        }
        return "fail";
    }
}

resources/views/ecommerce/product/index.blade.php
@extends('layouts.admin_layout')
@section('title') {{__('cp.categories')}}
@endsection
@section('css')
@endsection

@section('page_container')


    <div class="portlet light bordered">
        <div class="portlet-body">
            <div class="table-toolbar">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="btn-group">
                            <a href="{{url('admin/products/create')}}" style="margin-right: 5px"
                               class="btn sbold green">{{__('cp.add')}}
                                <i class="fa fa-plus"></i>
                            </a>
                            <button class="btn sbold blue btn--filter">{{__('cp.filter')}}
                                <i class="fa fa-search"></i>
                            </button>
                            <button class="btn sbold green event"  href="#activation" role="button"  data-toggle="modal">{{__('cp.active')}}
                                <i class="fa fa-check"></i>
                            </button>
                            <button class="btn sbold default event"  href="#cancel_activation" role="button"  data-toggle="modal">{{__('cp.not_active')}}
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>

                </div>
                <div class="box-filter-collapse">
                    <form class="form-horizontal" method="get" action="{{'products'}}">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group row">
                                    <label class="col-md-3 control-label">{{__('cp.category')}}</label>
                                    <div class="col-md-9">
                                        <select class="form-control" name="category_id" id="category" >
                                            <option >Select category</option>
                                            @foreach (\App\Models\ecommerce\Category::get() as $item)
                                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>


                            <div class="col-md-3">
                                <div class="form-group row">
                                    <label></label>{{__('cp.sub_category')}}</label>
                                    <div class="col-md-9">
                                        <select style="width: 120px;" class="form-control" name="sub_category_id" id="subcategory">
                                        </select>
                                    </div>
                                </div>
                            </div>


                            <div class="col-md-3">
                                <div class="form-group row">
                                    <label class="col-md-3 control-label">{{__('cp.status')}}</label>
                                    <div class="col-md-9">
                                        <select id="multiple2" class="form-control" name="status">
                                            <option value="">{{__('cp.all')}}</option>
                                            <option value="active" {{Request::get('status') == 'active' ? 'selected' : ''}}>{{__('cp.active')}}</option>
                                            <option value="not_active" {{Request::get('status') == 'not_active' ? 'selected' : ''}}>{{__('cp.not_active')}}</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn sbold blue">{{__('cp.search')}}
                                            <i class="fa fa-search"></i>
                                        </button>
                                        <a href="{{url('admin/products')}}" type="submit"
                                           class="btn sbold btn-default ">{{__('cp.reset')}}
                                            <i class="fa fa-refresh"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </form>
                </div>
                <br>
                <br>
            </div>


            <table class="table table-striped table-bordered table-hover table-checkable order-column" id="toolsTable">
                <thead>
                <tr>
                    <th>

                    </th>
                    <th> {{ucwords(__('cp.image'))}}</th>
                    <th> {{ucwords(__('cp.name'))}}</th>
                    <th> {{ucwords(__('cp.price'))}}</th>
                    <th> {{ucwords(__('cp.discount'))}}</th>
                    <th> {{ucwords(__('cp.availability'))}}</th>

                    {{--                    <th> {{ucwords(__('cp.status'))}}</th>--}}
                    <th> {{ucwords(__('cp.created'))}}</th>
                    {{--                    <th> {{ucwords(__('cp.action'))}}</th>--}}
                </tr>
                </thead>
                <tbody>
                @forelse($products as $product)
                    <tr class="odd gradeX" id="tr-{{$product->id}}">
                        <td>
                            <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                <input type="checkbox" class="checkboxes chkBox" value="{{$product->id}}" name="chkBox"/>
                                <span></span>
                            </label>
                        </td>

                        <td><img src="{{$product->logo}}" width="50px" height="50px"></td>

                        <td>{{$product->name}}</td>
                        <td>@if($product->priceOffer==$product->price) {{$product->price}} @else <del style="color: red;">{{$product->price}}</del> => {{$product->priceOffer}}  @endif</td>
                        <td>@if($product->finalDiscount>0) {{$product->finalDiscount}}% @else{{__('cp.no_discount')}} @endif</td>
                        <td style="color: {{$product->status=='active' ? "lime": 'red' }}">@if($product->status=='active') {{__('cp.available')}} @else {{__('cp.not_available')}} @endif</td>
                        {{--                        <td> <span class="label label-sm {{($category->status == "active")--}}
                        {{--                                ? "label-info" : "label-danger"}}" id="label-{{$category->id}}">--}}

                        {{--                                {{__('cp.'.$category->status)}}--}}
                        {{--                            </span>--}}
                        {{--                        </td>--}}

                        <td class="center">{{$product->created_at}}</td>

                        <td>
                            <div class="btn-group btn-action">
                                <a href="{{'products/'.$product->id.'/edit'}}"
                                   class="btn btn-xs blue tooltips" data-container="body" data-placement="top"
                                   data-original-title="{{__('cp.edit')}}"><i class="fa fa-edit"></i></a>

                            </div>

{{--                            <div class="btn-group btn-action">--}}
{{--                                <a href="{{'products/'.$product->id}}"--}}
{{--                                   class="btn btn-xs red tooltips" data-container="body" data-placement="top"--}}
{{--                                   data-original-title="{{__('cp.delete')}}"><i class="fa fa-remove"></i></a>--}}

{{--                            </div>--}}
                            <a href="#myModal{{$product->id}}" role="button"  data-toggle="modal" class="btn btn-xs red tooltips"><i class="fa fa-times" aria-hidden="true"></i></a>

                            <div id="myModal{{$product->id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                            <h4 class="modal-title">{{__('cp.delete')}}</h4>
                                        </div>
                                        <div class="modal-body">
                                            <p>{{__('cp.confirm')}} </p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn default" data-dismiss="modal" aria-hidden="true">{{__('cp.cancel')}}</button>
                                            <a href="#" onclick="delete_adv('{{$product->id}}','{{$product->id}}',event)"><button class="btn btn-danger">{{__('cp.delete')}}</button></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </td>

                    </tr>
                @empty
                    {{__('cp.no')}}
                @endforelse
                </tbody>
            </table>
        </div>
    </div>


@endsection

@section('scripts')
    <script>


        function delete_adv(id, iss_id, e) {
            e.preventDefault();
            console.log(id);
            console.log(iss_id);
            var url = 'products/'+id+'/delete';
            var csrf_token = '{{csrf_token()}}';
            $.ajax({
                type: 'get',
                headers: {'X-CSRF-TOKEN': csrf_token},
                url: url,
                data: {_method: 'get'},
                success: function (response) {
                    console.log(response);
                    if (response === 'success') {
                        $('#tr-' + id).hide(500);
                        $('#myModal' + id).modal('toggle');
                    } else {
                        // swal('Error', {icon: "error"});
                    }
                },
                error: function (e) {
                    // swal('exception', {icon: "error"});
                }
            });

        }




        $('.btn--filter').click(function () {
            $('.box-filter-collapse').slideToggle(500);
        });
    </script>
    <script type="text/javascript">
        $.ajaxSetup({
            headers: {

                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $(document).ready(function () {
            $('#category').on('change',function(e) {
                var cat_id = e.target.value;
                $.ajax({
                    url:"{{ url('subcat') }}",
                    type:"POST",
                    data: {
                        cat_id: cat_id,
                         _token: '{{csrf_token()}}'
                    },
                    dataType: 'json',
                    success:function (data) {
                        $('#subcategory').empty();
                        $.each(data.subcategories,function(index,subcategory){
                            $('#subcategory').append('<option value="'+subcategory.id+'">'+subcategory.name+'</option>');
                        })
                    }
                })
            });
        });
    </script>
@endsection